### ISSUE TITLE
Running "...-g" Successfully Causes Waydroid to Not Boot

### ISSUE THREAD

**Issue by levone1** [casualsnek/waydroid_script#1]
I'm ising Waydroid 1.1.1 on SailfishOS, according to https://github.com/lal883/tama-sailfish-waydroid-instructios and functions fine. After successfully running "python3 waydroid_extras.py -g", ("OpenGapps successfully installed" message), Waydroid now will not boot.

Status shows container running and session running, but never shows "ready" message, which would indicate that "show-full-ui" command will succeed. Also, "puddlejumper service" message never appears.

Any ideass how to troubleshoot?

**Comment by levone1** [comment]
update - tried again from scratch and working now... Not sure what happened last time ... Waydroid log showed "/init unable to link executable libbinder...file not found".  Libbinder was peesent with 644 in /var/lib/waydroid/rootfs... and in /apex/android.../lib64.

**Comment by meisme-dev** [comment]
having the same issue
