### ISSUE TITLE
the install instruction have one small think missing 

### ISSUE THREAD

**Issue by Idcrafter** [casualsnek/waydroid_script#112]
There is the requirements.txt missing after the -r which isn't working when not included

![grafik](https://github.com/casualsnek/waydroid_script/assets/50270538/a0ca030c-70c0-449b-a37a-94d88cde5fe7)

**Comment by nimaaskarian** [comment]
`python3 -m pip install -r requirements.txt`
although I recommend using venv:
```
git clone https://github.com/casualsnek/waydroid_script
cd waydriod_script
python3 -m venv .
./bin/pip install -r requirements.txt
sudo ./bin/python3 main.py
```

**Comment by Idcrafter** [comment]
i also would suggest changing it in the README because it could create confusion for not so experienced people and yes i always do venv because otherwise could i brick my os

**Comment by casualsnek** [comment]
Thanks for feedback, i'll test and update README asap !
