### ISSUE TITLE
Force app to load as ARM?

### ISSUE THREAD

**Issue by ckcr4lyf** [casualsnek/waydroid_script#114]
I am trying to load an app which has compiled C code (called via JNI), but only for ARM.

On startup I am guessing it detects x86 and the main app works, but there is no corresponding library for x86, so that part fails.

Is it possible to force the app to detect and launch in an ARM mode? I tried "just using" libndk / libhoudini, didn't seem to work (as in it still starts in x86 mode).

**Comment by ayasa520** [comment]
`pm install --abi %ARCH% %APK_PATH%`

**Comment by ckcr4lyf** [comment]
Thanks a lot, it works perfectly!

For anyone else using this as a reference, run the command in  the adb shell of the waydroid device:

```
pm install --abi arm64-v8a [APK_PATH]
```

I am using libhoudini and it seems to correctly work.

**Comment by Nikitf777** [comment]
I tried it, and it says "ABI arm64-v8a not supported on this device". Is it a hardware issue or I need to setup something?

**Comment by ckcr4lyf** [comment]
> Is it a hardware issue or I need to setup something?

It's possible, very hard to say without any more info. Can you share details about the host you're running this on? (OS, CPU etc.)

**Comment by Nikitf777** [comment]
I fixed this. As it turned out, I have to manually setup libhoudini (I though it is included out of the box). That's why I asked about the need of setup something before executing the command.
