### ISSUE TITLE
Libhoudini not able to fully run a game

### ISSUE THREAD

**Issue by d-s-dc** [casualsnek/waydroid_script#116]
I am able to install libhoudini on the waydroid using the script, thanks for that. I am trying to run an arm based game which I installed from the gapps. The game is stuck at an age prompt. On mobile it opens a tab to select month and year but is not doing on waydroid. The waydroid is running fine except from getting stuck at that.

![image](https://github.com/casualsnek/waydroid_script/assets/68206552/73b1d841-e367-4924-a20b-b456a9d4c8da)

Is there any way to do something, any log files I can look for? The waydroid.log file didn't show anything skeptical (to my knowledge). I also tried lidndk and faced the same thing. I am running Android 11 GAPPS version of waydroid.

**Comment by ayasa520** [comment]
It's not "stuck", it's because click event was not responded correctly. And `fake_touch` doesn't work for all apps.
You can use [Scrcpy](https://github.com/Genymobile/scrcpy) for touch simulation.

![image](https://github.com/casualsnek/waydroid_script/assets/55699692/32d5c032-afe6-4bae-b339-56a04363305e)

**Comment by d-s-dc** [comment]
Hi thanks for replying. I downloaded scrcpy, but how to connect it to waydroid?

**Comment by d-s-dc** [comment]
Thanks for that, I am able to proceed in the game. But now in waydroid, I have to do everything with the mouse, is there any way to control things with the keyboard?

**Comment by ayasa520** [comment]
> Thanks for that, I am able to proceed in the game. But now in waydroid, I have to do everything with the mouse, is there any way to control things with the keyboard?

For games that don't directly support keyboards, you can use [QtScrcpy](https://github.com/barry-ran/QtScrcpy/#mapping-keys) for keyboard mapping.

**Comment by d-s-dc** [comment]
I have connected waydroid with QtScrcpy and the resolution is fine but the frames drop while playing the game. Is there anything else?

**Comment by d-s-dc** [comment]
At the end, I am using a script [from stackoverflow](https://stackoverflow.com/questions/3649874/how-can-i-get-the-keyboard-state-in-linux/49840783#49840783) to catch keyboard and `ydotool` to simulate mouse movements. It's not smooth but is fine. I really hope some proper solution to run these ARM based games comes out. Since my original problem has been resolved (using scrcpy), I am closing this.

Thanks for all the help!
