### ISSUE TITLE
installing libndk, uninstalling libndk, installing houdini, and then uninstalling houdini leaves libndk uninstallable

### ISSUE THREAD

**Issue by Kodehawa** [casualsnek/waydroid_script#119]
Title. It's a bit of a cursed issue. 

I first installed libndk, then wanted libhoudini to test some performance issues on Azur Lane. 

Tried it, it worked fine, but used too much CPU, so I did the following:
- uninstall libhoundini, check that no translation layer is installed
- install libndk

The result was going back to libhoudini. If I uninstall libhoudini again (NOT ndk!) I'm left with no translation layer again. Trying to install libndk yields the script installing libhoudini for some reason (even though it says it's installing ndk, and honestly it should be doing that).

You can check this with AIDA 64, as AIDA64 says the CPU is a generic ARM CPU using libndk, while with libhoudini it identifies it as the correct CPU name, but has arm64 capabilities.

My guess is that it's leaving some residual files somewhere, but I honestly have no clue why this would even happen.

Thing is, I'm not *completely* sure of this. I see libndk on /system/lib64 and /system/lib, but no libhoudini. The *behavior* of the applications is completely different, though?

**Comment by Kodehawa** [comment]
![image](https://github.com/casualsnek/waydroid_script/assets/20606963/66f188d5-ab0b-4a32-bc01-373d2bd50a8c)
uninstalled libhoudini ^

![image](https://github.com/casualsnek/waydroid_script/assets/20606963/6ae83086-a61e-4317-8ece-70b7edc10940)
^ installed libndk, but still using houdini (restarted container manually separately)

**Comment by ayasa520** [comment]
> can also somewhat confirm libhoudini is still being used because Azur Lane is running better than with ndk, but it uses a lot of CPU -- kind of confused honestly, is there a better way to check?

`grep "ro.dalvik.vm.native.bridge" /var/lib/waydroid/waydroid_base.prop`

**Comment by Kodehawa** [comment]
> > can also somewhat confirm libhoudini is still being used because Azur Lane is running better than with ndk, but it uses a lot of CPU -- kind of confused honestly, is there a better way to check?
> 
> `grep "ro.dalvik.vm.native.bridge" /var/lib/waydroid/waydroid_base.prop`

Shows libndk, so closing. Now I'm confused by the fact the AIDA64 CPU string used to be different under libndk before I installed libhoudini. Oh well, I'm gonna trust the prop and say I'm tripping instead.
