### ISSUE TITLE
ERROR: Cannot locate waydroid config file, reinit wayland and try again!

### ISSUE THREAD

**Issue by Gammelstulle** [casualsnek/waydroid_script#129]
Hi,

if i try to complete the scrip on POPOS 22.04, i get this othe error:
ERROR: Cannot locate waydroid config file, reinit wayland and try again!

Not shure what wayland has to do whit waydroid... 
I activated wayland via the gnome config abd restart, same issue.

Any Idea or im just blind and miss something in der doku?

**Comment by casualsnek** [comment]
Opps, a mistake ! Is your waydroid running when you start the script ?

**Comment by Gammelstulle** [comment]
> Opps, a mistake ! Is your waydroid running when you start the script ?

it is not installed ( not run at all) *swt*

**Comment by SonGoku90** [comment]
Hello, I have the same in mint 22.1 cinnamon
