### ISSUE TITLE
sqlite3 issue when trying to run [sudo python3 waydroid_extras.py -i]

### ISSUE THREAD

**Issue by AraiDai** [casualsnek/waydroid_script#13]
Got Gapps installed, ran everything, working just fine.
But then I reach this spot and the script won't proceed.
Am I missing something?
![Screenshot from 2021-11-22 23-35-14](https://user-images.githubusercontent.com/67785468/142975985-2af7d986-61f2-4b84-bef8-b75e15cea0f2.png)

**Comment by casualsnek** [comment]
Have you installed sqlite on your system ? Install sqlite using your package manager and run the script again !

**Comment by AraiDai** [comment]
Whoops! Yeah I figured I missed something. Now that's working all fine and dandy! I'll let you know if there's something else broken. :D But thanks for the lightning quick response.

**Comment by AraiDai** [comment]
Alright now all I have to do is wait out the Google Device thing :D Thanks for making this stuff! So usually it takes around half an hour maybe to get it no?
