### ISSUE TITLE
getting android id fails

### ISSUE THREAD

**Issue by emhl** [casualsnek/waydroid_script#15]
when trying to run `udo python3 waydroid_extras.py -i`
it fails with the following traceback:
```
emil@pop-thinkpad:~/waydroid_script/waydroid_script$ sudo python3 waydroid_extras.py -i
Traceback (most recent call last):
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 566, in <module>
    main()
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 559, in main
    get_android_id()
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 183, in get_android_id
    queryout = subprocess.check_output(["sqlite3", "/var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db", sqs.strip()], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
```

**Comment by emhl** [comment]
`waydroid_extras.py -l` fails as well
```
emil@pop-thinkpad:~/waydroid_script/waydroid_script$ sudo python3 waydroid_extras.py -l
==> Found system image: /var/lib/waydroid/images/system.img
==> Resizing system image....
==> Unmounting .. 
==> Extracting archive...
==> Chmodding...
==> Copying library files ...
==> Adding arch in build.prop
==> Adding entry to init.rc
==> Set android version: 11
Traceback (most recent call last):
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 566, in <module>
    main()
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 563, in main
    install_houdini()
  File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 372, in install_houdini
    with open(init_path, "r") as initfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/waydroidimage/system/etc/init/hw/init.rc'
```

**Comment by casualsnek** [comment]
> when trying to run `udo python3 waydroid_extras.py -i` it fails with the following traceback:
> 
> ```
> emil@pop-thinkpad:~/waydroid_script/waydroid_script$ sudo python3 waydroid_extras.py -i
> Traceback (most recent call last):
>   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 566, in <module>
>     main()
>   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 559, in main
>     get_android_id()
>   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 183, in get_android_id
>     queryout = subprocess.check_output(["sqlite3", "/var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db", sqs.strip()], stderr=subprocess.STDOUT)
>   File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.9/subprocess.py", line 505, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
> ```

install sqlite through your distribution's package manager and try again, it should work after that !

**Comment by casualsnek** [comment]
> > when trying to run `udo python3 waydroid_extras.py -i` it fails with the following traceback:
> > ```
> > emil@pop-thinkpad:~/waydroid_script/waydroid_script$ sudo python3 waydroid_extras.py -i
> > Traceback (most recent call last):
> >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 566, in <module>
> >     main()
> >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 559, in main
> >     get_android_id()
> >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 183, in get_android_id
> >     queryout = subprocess.check_output(["sqlite3", "/var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db", sqs.strip()], stderr=subprocess.STDOUT)
> >   File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
> >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> >   File "/usr/lib/python3.9/subprocess.py", line 505, in run
> >     with Popen(*popenargs, **kwargs) as process:
> >   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
> > ```
> 
> install sqlite through your distribution's package manager and try again, it should work after that !

looks like you are trying to install libhoudini on Android 10 waydroid image, libhoudini does not really work on Android 10, so the installation is designed only for android 11 images.
Use libndk if you are using Android 10

**Comment by emhl** [comment]
Thanks. that worked perfectly. i probably should've read the description of the libhoudini install better :D.

**Comment by Heath123** [comment]
> > > when trying to run `udo python3 waydroid_extras.py -i` it fails with the following traceback:
> > > ```
> > > emil@pop-thinkpad:~/waydroid_script/waydroid_script$ sudo python3 waydroid_extras.py -i
> > > Traceback (most recent call last):
> > >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 566, in <module>
> > >     main()
> > >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 559, in main
> > >     get_android_id()
> > >   File "/home/emil/waydroid_script/waydroid_script/waydroid_extras.py", line 183, in get_android_id
> > >     queryout = subprocess.check_output(["sqlite3", "/var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db", sqs.strip()], stderr=subprocess.STDOUT)
> > >   File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
> > >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> > >   File "/usr/lib/python3.9/subprocess.py", line 505, in run
> > >     with Popen(*popenargs, **kwargs) as process:
> > >   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
> > >     self._execute_child(args, executable, preexec_fn, close_fds,
> > >   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
> > >     raise child_exception_type(errno_num, err_msg, err_filename)
> > > FileNotFoundError: [Errno 2] No such file or directory: 'sqlite3'
> > > ```
> > 
> > 
> > install sqlite through your distribution's package manager and try again, it should work after that !
> 
> looks like you are trying to install libhoudini on Android 10 waydroid image, libhoudini does not really work on Android 10, so the installation is designed only for android 11 images. Use libndk if you are using Android 10

You can use Android 11 on Waydroid?
