### ISSUE TITLE
Blue Archive (GLOBAL) hang and crash after getting past the Touch to start screen

### ISSUE THREAD

**Issue by qwerty12356-wart** [casualsnek/waydroid_script#168]
OS: Linux Mint 21.3 (Wayland session)
Running the script with only installing libhoudini lead to a black screen and crash on game open.
Only partially work (see title) when installing both libhoudini and libndk (though i havent tried it with only libndk).
If anyone can help i'd gladly appreciate it.

EDIT: Also doesnt work with only one of them

**Comment by qwerty12356-wart** [comment]
Closed. Fixes available

**Comment by qwerty12356-wart** [comment]
Closed. Fixes available.

**Comment by AozoraDev** [comment]
Where the fixes?

**Comment by qwerty12356-wart** [comment]
> Where the fixes?

waydroid/waydroid#788
I have posted the fix here.

**Comment by AozoraDev** [comment]
Sweet! Thanks!
