### ISSUE TITLE
Waydroid gets stuck on boot/startup screen after installation

### ISSUE THREAD

**Issue by Sphirye** [casualsnek/waydroid_script#171]
After running the waydroid script via terminal interface, running `waydroid show-full-ui` will keep loading/booting up forever, however the console shows no error or additional info more than this:

```bash
user@fedora:~$ waydroid show-full-ui
[00:38:42] Starting waydroid session
[gbinder] Service manager /dev/binder has appeared
```

Environment:
```
Selected apps during script installation: gapps, libdnk, magisk and smartdock
Waydroid selected android type: GAPPS
OS: Fedora Linux 40 (Workstation Edition) x86_64 
Kernel: 6.8.11-300.fc40.x86_64 
DE: GNOME 46.2
CPU: AMD Ryzen 5 5500U with Radeon Graphics
``

Feel free to ask for any additional related log!

**Comment by mt190502** [comment]
Update: i installed smartdock 1.12.1 version and i clear old appdata from settings. Version 1.12.1 is worked successfully

**Comment by Sphirye** [comment]
> Update: i installed smartdock 1.12.1 version and i clear old appdata from settings. Version 1.12.1 is worked successfully

Can you explain how did you proceed?

**Comment by Yaoka01** [comment]
> Update: i installed smartdock 1.12.1 version and i clear old appdata from settings. Version 1.12.1 is worked successfully

how even u can go to setting while stuck on boot looping?
