### ISSUE TITLE
Feature Request: Set up xtmapper

### ISSUE THREAD

**Issue by Aman9das** [casualsnek/waydroid_script#180]
It needs magisk delta and some patches..

Some other open source keymapper could be useful as well ;)

**Comment by YogSottot** [comment]
> It needs magisk delta

It is not true.  Magisk is not required for activation as the console is rooted out of the box
```sudo waydroid shell```

Also it only requires a patched cage, which has absolutely nothing to do with waydroid.  
https://github.com/Xtr126/wayland-getevent/blob/main/README-alt.md

**Comment by Aman9das** [comment]
I'm happy to be corrected. And these workarounds demonstrate why xtmapper configuration is even more necessary. It's a complicated thing to figure out
