### ISSUE TITLE
Magisk app run as a system app (warning)

### ISSUE THREAD

**Issue by osering** [casualsnek/waydroid_script#21]
Magisk app (which can be upgraded to newest v.23.0 unlike Magisk manager which does no update from v.20.4 using Direct install) on start gives **warning**:

**Abnormal state
Running this app as a system app is not supported. Please revert the app to a user app.**
OK

Should I let it be like this or try using some app to revert it?

**Comment by casualsnek** [comment]
you can safely ignore this warning !
