### ISSUE TITLE
Install under Ubuntu Touch (UBports)

### ISSUE THREAD

**Issue by osering** [casualsnek/waydroid_script#22]
**[1] Install commands for Ubuntu Touch** (UBports, Halium-9.0, Xiaomi Mi8 - dipper)
```
sudo apt install lzip git
sudo apt install -y python3-pip
git clone https://github.com/casualsnek/waydroid_script
cd waydroid_script
sudo python3 -m pip install -r requirements.txt
sudo python3 waydroid_extras.py [-m/-i/-g/-n/-h]
```

**[2] UBports by default makes small (1.4G) /data partition,** so, when installing waydroid_script you can face:
==> Installing magisk now ...
OSError: [Errno 28] No space left on device

Check in Terminal or SSH
```
sudo df -h
```
/dev/loop1                     1,4G  1,4G     0 100% /var/lib/waydroid/rootfs
/dev/loop3                     1,4G  1,4G     0 100% /tmp/waydroidimage
```
sudo losetup /dev/loop1
sudo losetup /dev/loop3
```

**[3] CURE: increase Waydroid /data image size (using ADB)**
```
1) reboot to custom recovery (TWRP, OrangeFox, UBports) by "fastboot reboot recovery" etc.
2) adb shell ## connect with adb
3) mount -o rw /dev/block/by-name/userdata /data ##mount /data
4) cd /data/system-data/var/lib/waydroid/images ## cd /data
5) dd if=/data/system-data/var/lib/waydroid/images/system.img of=/sdcard/waydroid-system.img status=progress ## just for safety make copy to be able to revert
6) e2fsck -f system.img ##check image health
7) resize2fs -p system.img 5G ##resize /data to 5GB (you can choose any other size)
8) reboot system
```

**Comment by casualsnek** [comment]
Thanks, now the script will not resize image blindly instead images will be resized as required !

**Comment by xingyujie** [comment]
Thanks 👍
