### ISSUE TITLE
Magisk

### ISSUE THREAD

**Issue by xAffan** [casualsnek/waydroid_script#27]
Since WSA and Waydroid function almost very similarly, we can probably use a project called "MagiskOnWSA" and port it to wayland for proper magisk support on waydroid :3
https://github.com/LSPosed/MagiskOnWSA

**Comment by casualsnek** [comment]
> Since WSA and Waydroid function almost very similarly, we can probably use a project called "MagiskOnWSA" and port it to wayland for proper magisk support on waydroid :3 https://github.com/LSPosed/MagiskOnWSA

i am trying that and other things by myself but never got to the point where magisk gets initialized ! Hopefully we get magisk soon

**Comment by casualsnek** [comment]
By the way magisk thread is at https://github.com/casualsnek/waydroid_script/issues/24
I recommend using it so that there are not multiple issues created for same thing !
