### ISSUE TITLE
Should downloaded files be placed in /tmp?

### ISSUE THREAD

**Issue by SamLukeYes** [casualsnek/waydroid_script#29]
/tmp is cleared across reboots. At least on Arch Linux, it is actually a tmpfs that is on RAM. Every time I re-init waydroid and reinstall libhoudini, the script re-downloads the tarball. Perhaps it would be better if the downloaded files are placed in persistent directories, such as /var/cache and /var/tmp.

BTW, some common external downloaders, such as wget and aria2, would be more robust and allow continuation.

**Comment by casualsnek** [comment]
> /tmp is cleared across reboots. At least on Arch Linux, it is actually a tmpfs that is on RAM. Every time I re-init waydroid and reinstall libhoudini, the script re-downloads the tarball. Perhaps it would be better if the downloaded files are placed in persistent directories, such as /var/cache and /var/tmp.

Thanks, i think i could use XDG_CACHE_DIR/waydroid_script for storing the downloaded files !

> BTW, some common external downloaders, such as wget and aria2, would be more robust and allow continuation.
I think it can be done with requests library instead of depending on external binaries !

I will probably push the changes you mentioned today :)

**Comment by casualsnek** [comment]
I just pushed a change that should download file in /home/user/.cache/waydroid_script/downloads directory, can you check if its working fine and close the issue if you are ok with the new changes 1

**Comment by SamLukeYes** [comment]
> I just pushed a change that should download file in /home/user/.cache/waydroid_script/downloads directory, can you check if its working fine and close the issue if your issue is solved with the new change !

Hmm, I tried installing Magisk for testing. The downloaded files exists in ~/.cache/waydroid_script/downloads as expected, but there's still something wrong:
```
==> Installing magisk now ...
Traceback (most recent call last):
  File "/usr/bin/waydroid-extras", line 595, in <module>
    main()
  File "/usr/bin/waydroid-extras", line 590, in main
    install_magisk()
  File "/usr/bin/waydroid-extras", line 507, in install_magisk
    shutil.copyfile(os.path.join(extract_to, arch_dir, "magiskinit{arch}".format(arch=arch)),
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/waydroidimage/sbin/magiskinit'
```

**Comment by casualsnek** [comment]
> > I just pushed a change that should download file in /home/user/.cache/waydroid_script/downloads directory, can you check if its working fine and close the issue if your issue is solved with the new change !
> 
> Hmm, I tried installing Magisk for testing. The downloaded files exists in ~/.cache/waydroid_script/downloads as expected, but there's still something wrong:
> 
> ```
> ==> Installing magisk now ...
> Traceback (most recent call last):
>   File "/usr/bin/waydroid-extras", line 595, in <module>
>     main()
>   File "/usr/bin/waydroid-extras", line 590, in main
>     install_magisk()
>   File "/usr/bin/waydroid-extras", line 507, in install_magisk
>     shutil.copyfile(os.path.join(extract_to, arch_dir, "magiskinit{arch}".format(arch=arch)),
>   File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/waydroidimage/sbin/magiskinit'
> ```

are you using android 11 images ? Since i have not got magisk to work properly on a11, i have not made magisk installation compatible with a11 !  This error is most likely due to missing sbin directory on android 11

**Comment by SamLukeYes** [comment]
Oh yes, I'm using the Android 11 image. Tried installing libhoudini later, and it works as expected.
