### ISSUE TITLE
Can't install Gapps

### ISSUE THREAD

**Issue by foxrus** [casualsnek/waydroid_script#32]
OSError: [Errno 28] No space left on device: '/tmp/waydroidimage/system/priv-app/GoogleFeedback'
Can you tell me what it could be?

**Comment by casualsnek** [comment]
Are you on any mobile linux os by any chance ?

**Comment by foxrus** [comment]
No, I am using ubuntu 21.10

**Comment by casualsnek** [comment]
Looks like resizing image had failed !, can you try running script after stopping waydroid properly

if that does not work open waydroid_script.py  goto line 141 and change ```resize_img(system_img, "{}M".format(img_size+500))```  to ```resize_img(system_img, "6G")``` and run the script again and see if it works.

Also, are there any any other warnings or error messages in terminal window ?

**Comment by foxrus** [comment]
It worked, thank you.
