### ISSUE TITLE
Cant get android device ID

### ISSUE THREAD

**Issue by tarithj** [casualsnek/waydroid_script#35]
I followed the README but I cant get the device id

![image](https://user-images.githubusercontent.com/29999281/152674780-58231ad6-aa0d-463a-842d-f106f9673576.png)

**Comment by casualsnek** [comment]
After installing gapps have you ran waydroid and tried to open play store ? If you have not done that, open play store at least once and try running the script again !

**Comment by tarithj** [comment]
Nope, tried it still didnt work

**Comment by KevinBowen0** [comment]
I'm seeing this same issue. I've tried opening waydroid and running the play store, tried restarting the container, no luck. I'm running on Fedora 35, using the versions from here: https://copr.fedorainfracloud.org/coprs/aleasto/waydroid/

**Comment by SonyaCore** [comment]
i have to same issue
![image](https://user-images.githubusercontent.com/66337103/164424068-0308031e-467a-40e0-983a-d5b346204471.png)

**Comment by kibo1no1shirei-kan** [comment]
yeah also has this issue can just the waydroid devs do it like anbox which already has a play store licence

**Comment by kibo1no1shirei-kan** [comment]
it also seems that the home directory is empty

**Comment by kibo1no1shirei-kan** [comment]
it looks like after a reebot the id becomes visible

**Comment by mudiagauwojeya** [comment]
I am having similar issue. I have started playstore more than once while waydroid was running and ran the script again but it didn't show me the `id`. I have also tried rebooting but no success with getting the `id`.

**Comment by Abdullah-Alhariri** [comment]
same issue

**Comment by sduensin** [comment]
Seems waydroid now writes data to:

`~/.local/share/waydroid/data/data/com.google.android.gsf/databases/gservices.db` 

and not to where waydroid_script expects:

`/var/lib/waydroid//data/data/com.google.android.gsf/databases/gservices.db`

**Comment by sduensin** [comment]
Another thing to check for those of you having problems...   Be sure networking is functioning inside waydroid.  If the browser can't reach Google, neither can Play.  Networking has to function to get a device ID.

**Comment by tonmoy998** [comment]
correct .Edit some codes.
cd stuffs/
vi android_id.py
replace "/var/lib/waydroid//data/data/com.google.android.gsf/databases/gservices.db" by "/home/tonmoy/.local/share/waydroid/data/data/com.google.android.gsf/databases/gservices.db"
In my case the user name is Tonmoy.There it will be your user name.
![Screenshot_20230430_171602](https://user-images.githubusercontent.com/74363531/235350176-6e63e388-7b3a-4226-9227-6a11180740b4.png)

100% working
![Screenshot_20230430_172112](https://user-images.githubusercontent.com/74363531/235350277-7595d1ac-faeb-488f-9aef-69619df0bb01.png)

**Comment by tonmoy998** [comment]
Here is the proof : )

![Screenshot_20230430_172433](https://user-images.githubusercontent.com/74363531/235350370-bec036dc-6b02-4499-a449-f7d8e9b960ec.png)

**Comment by tarithj** [comment]
Fixed for me too thanks!

**Comment by Duxon** [comment]
Workaround does not work anymore. Here is a [new issue](https://github.com/casualsnek/waydroid_script/issues/193) for now being able to get the device ID.
