### ISSUE TITLE
Magisk Direct Install Missing

### ISSUE THREAD

**Issue by YasirRWebDesigner** [casualsnek/waydroid_script#71]
System Info

**OS:** Arch
**DE:** Sway/Hyprland
**Kernel:** Linux 5.15.94-1-lts

So I tried to install magisk but I don't get the Direct Install into system partition option. What to do?
![swappy-20230218_032820](https://user-images.githubusercontent.com/32537564/219812663-2d981787-6fba-434b-adaf-fc665d50858b.png)
![swappy-20230218_032842](https://user-images.githubusercontent.com/32537564/219812681-522082b5-10bf-44d2-9ccb-54b252992ab1.png)

**Comment by IMxingyus** [comment]
I also encountered the same problem

**Comment by ayasa520** [comment]
I think this is related to the kernel, please switch to `linux-xanmod-anbox` and try again

**Comment by Errant404** [comment]
I also encountered the same problem, and i am using linux zen kernel

**Comment by Errant404** [comment]
archlinux seems to have other requirements to use magisk-delta, see [this](https://github.com/nitanmarcel/waydroid-magisk#arch-linux)

**Comment by ayasa520** [comment]
I've never had a issue with the official Manjaro kernel or linux-zen

**Comment by ayasa520** [comment]
Could you please change the permissions of `/var/lib/waydroid/overlay/system/etc/init/bootanim.rc` to 644 and try again
