### ISSUE TITLE
When installing OpenGApps I get an error.

### ISSUE THREAD

**Issue by vrmaurice** [casualsnek/waydroid_script#72]
I just followed the guide on README.

When running `sudo python3 main.py -i`, I just get this error: `ERROR: Cannot access gservices.db, make sure gapps is installed and waydroid was started at least once after installation and make sure waydroid is running !`

Waydroid is showing the GUI and I have installed gapps as I have ran the commands needed for installation.

I'm on Fedora 37 with GNOME.

**Comment by Xandor19** [comment]
Having the same issue here, Ubuntu 22.04 with GNOME 42. I installed Waydroid GAPPS and now was trying to register the device with this script

**Comment by Xandor19** [comment]
Check the Issue #68, the 2nd comment worked for me

**Comment by vrmaurice** [comment]
For me too, thanks
