### ISSUE TITLE
libndk link is down

### ISSUE THREAD

**Issue by mac1202** [casualsnek/waydroid_script#74]
Hello trying to install libndk the download failed. 
Directly open the link(https://www.dropbox.com/s/eaf4dj3novwiccp/libndk_translation_Module-c6077f3398172c64f55aad7aab0e55fad9110cf3.zip?dl=1) in browser give me a 404 error.

**Comment by ayasa520** [comment]
Use https://github.com/supremegamers/vendor_google_proprietary_ndk_translation-prebuilt if you are willing to try

**Comment by LegacyGamerHD** [comment]
Well i took it down because i needed the space for other stuff
