### ISSUE TITLE
Fail to install it.

### ISSUE THREAD

**Issue by laichiaheng** [casualsnek/waydroid_script#8]
usage: waydroid_extras.py [-h] [-g] [-n] [-i] [-m]
waydroid_extras.py: error: unrecognized arguments: [-i/-g/-n/-h]

**Comment by laichiaheng** [comment]
Never mind, just following the steps below.
May be you should remove this line?

**Comment by casualsnek** [comment]
> Never mind, just following the steps below. May be you should remove this line?

This was intended to show the available arguments, if this creates any more confusion i may rephrase it !
