### ISSUE TITLE
Installing libhoudini doesn't do anything.

### ISSUE THREAD

**Issue by Kodehawa** [casualsnek/waydroid_script#82]
Title. Trying to install libhoudini (or libndk for that matter) does nothing and after a container restart the aarch64 nor armv7 ABI is not enabled. I've tried several times and even tried rebooting the entire system to no avail.

Tried installing a game that uses aarch64 and it didn't work either, so the ABI detect is correct.

![image](https://user-images.githubusercontent.com/20606963/231319125-f5d8b9b6-c3d9-4c95-9a7f-8930587e2a0a.png)

![image](https://user-images.githubusercontent.com/20606963/231321846-4eb349bd-a8a3-4cfd-880b-a5f9a3f6f3be.png)

**Comment by Kodehawa** [comment]
Oh, running what's described in https://github.com/casualsnek/waydroid_script/pull/79 fixes it (`waydroid upgrade -o`)

Please merge it.

**Comment by mak448a** [comment]
Please close since the pull request was merged
