### ISSUE TITLE
Remove libhoudini to install libndk

### ISSUE THREAD

**Issue by enderprism** [casualsnek/waydroid_script#89]
How can I remove libhoudini? I changed my mind after installing it, but I don't know how to _uninstall_ it.

**Comment by creeloper27** [comment]
as the [README explains](https://github.com/casualsnek/waydroid_script#command-line):
`sudo venv/bin/python3 main.py remove libhoudini` while inside the cloned repository and virtual python envirment

**Comment by enderprism** [comment]
thanks!
