### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by DaRandomCube** [casualsnek/waydroid_script#93]
os:ubuntu 23.04
arch:amd64
kernel:Linux 6.2.0-20-generic
waydroid image : 18.1-20230422-GAPPS-waydroid_x86_64
![Screenshot from 2023-06-06 23-16-08](https://github.com/casualsnek/waydroid_script/assets/93283139/02d99fe2-1595-4cea-8c26-d31d967fb8db)

**Comment by TriMoon** [comment]
same here no idea if i should risk using the mentioned option at end...

**Comment by TriMoon** [comment]
I just used the below, hope it didn't break my Kubuntu 23.04 system:
```
sudo python3 -m pip install -r requirements.txt --break-system-packages
```

**Comment by DaRandomCube** [comment]
thanks @TriMoon, here is the fix
```
sudo python3 -m pip install -r requirements.txt --break-system-packages
```

**Comment by casualsnek** [comment]
> thanks @TriMoon, here is the fix
> 
> ```
> sudo python3 -m pip install -r requirements.txt --break-system-packages
> ```

You can also give updated readme instructions a try, it makes use of venv instead which reduces conflicts with package manager installed python packages !

**Comment by DaRandomCube** [comment]
> > thanks @TriMoon, here is the fix
> > ```
> > sudo python3 -m pip install -r requirements.txt --break-system-packages
> > ```
> 
> You can also give updated readme instructions a try, it makes use of venv instead which reduces conflicts with package manager installed python packages !

idk how to use venv + i'm not good at english atm

**Comment by ChuJiani** [comment]
> > > thanks @TriMoon, here is the fix
> > > ```
> > > sudo python3 -m pip install -r requirements.txt --break-system-packages
> > > ```
> > 
> > You can also give updated readme instructions a try, it makes use of venv instead which reduces conflicts with package manager installed python packages !
> 
> idk how to use venv + i'm not good at english atm

Just follow README.md and all things will be ok
