### ISSUE TITLE
Can't install libhoudini

### ISSUE THREAD

**Issue by msmalik681** [casualsnek/waydroid_script#97]
I get this error on linux mint 21.1

Traceback (most recent call last):
  File "/home/malik/Desktop/libhoundini/waydroid_script-main/main.py", line 2, in <module>
    from InquirerPy import inquirer
ModuleNotFoundError: No module named 'InquirerPy'

**Comment by casualsnek** [comment]
Have you installed the dependencies with ```python3 -m pip install -r requirements.txt``` ?

**Comment by msmalik681** [comment]
just did that and I got the same thing

**Comment by rc17060313** [comment]
same issue here

**Comment by casualsnek** [comment]
> Just did that and I got the same thing its weird because I have installed this before.
> 
> Could you help me with instructions on how to manually update it without the script please.

do it with ```sudo python3 -m pip install InquirerPy``` and see if it works !

**Comment by rc17060313** [comment]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

**Comment by rc17060313** [comment]
sudo python3 -m pip install InquirerPy --break-system-packages
then
sudo pip install tqdm --break-system-packages

**Comment by rc17060313** [comment]
> sudo python3 -m pip install InquirerPy --break-system-packages then sudo pip install tqdm --break-system-packages

this works

**Comment by msmalik681** [comment]
Already had that dependency satisfied so not sure why it worked now the only thing i did different was running it from downloads instead of the desktop.

I will close this issue down but please if you could help me figure out how to apply the arm libhoudini manually I would forever appreciate it.

**Comment by wh1ter0z3** [comment]
Had similar issue on debian12 , fixed by using this command **source venv/bin/activate** 
so the proper way for me was:

git clone https://github.com/casualsnek/waydroid_script
cd waydroid_script
python3 -m venv venv
source venv/bin/activate
venv/bin/pip install -r requirements.txt
sudo venv/bin/python3 main.py

**Comment by dieperdev** [comment]
> sudo python3 -m pip install InquirerPy --break-system-packages then sudo pip install tqdm --break-system-packages

Worked for me. Cheers.
